# Generated by Django 4.2.17 on 2024-12-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(null=True)),
            ],
        ),
    ]
